In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/table09_combined.csv")

In [3]:
df.shape

(6758, 14)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6758 entries, 0 to 6757
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   rundate                       6758 non-null   str
 1   this_period                   6758 non-null   int64
 2   last_period                   6758 non-null   int64
 3   reporting_airport_group_name  6758 non-null   str
 4   reporting_airport_name        6758 non-null   str
 5   total_pax_this_period         6758 non-null   int64
 6   total_pax_last_period         6758 non-null   int64
 7   total_pax_percent             6758 non-null   str
 8   terminal_pax_this_period      6758 non-null   int64
 9   terminal_pax_last_period      6758 non-null   int64
 10  terminal_pax_percent          6758 non-null   str
 11  transit_pax_this_period       6758 non-null   int64
 12  transit_pax_last_period       6758 non-null   int64
 13  transit_pax_percent           6758 non-null   str
dtypes: int64(8), str(6)
memory usage: 1.2 MB

In [5]:
df["this_period"].min(), df["this_period"].max()

(np.int64(201501), np.int64(2017009))

In [6]:
sorted(df["this_period"].unique())[-20:]

[np.int64(202507),
 np.int64(202508),
 np.int64(202509),
 np.int64(202510),
 np.int64(202511),
 np.int64(202512),
 np.int64(2016005),
 np.int64(2016006),
 np.int64(2016007),
 np.int64(2016008),
 np.int64(2016009),
 np.int64(2017001),
 np.int64(2017002),
 np.int64(2017003),
 np.int64(2017004),
 np.int64(2017005),
 np.int64(2017006),
 np.int64(2017007),
 np.int64(2017008),
 np.int64(2017009)]

In [7]:
df.loc[df["this_period"] > 999999, "this_period"].value_counts().sort_index()

this_period
2016005    55
2016006    55
2016007    54
2016008    54
2016009    54
2017001    55
2017002    55
2017003    54
2017004    52
2017005    52
2017006    53
2017007    52
2017008    52
2017009    52
Name: count, dtype: int64

In [8]:
df["this_period_clean"] = df["this_period"].astype(str).str.replace(
    r"^(\d{4})00(\d)$",
    r"\1\2",
    regex=True
)

df["this_period_clean"] = df["this_period_clean"].astype(int)

In [9]:
df["this_period_clean"].min(), df["this_period_clean"].max()

(np.int64(20165), np.int64(202512))

In [10]:
df["this_period_clean"] = df["this_period"].astype(str).str.replace(
    r"^(\d{4})0(\d{2})$",
    r"\1\2",
    regex=True
).astype(int)

df["this_period_clean"].min(), df["this_period_clean"].max()

(np.int64(201501), np.int64(202512))

In [11]:
df["this_period_clean"].nunique()

132

In [12]:
df["date"] = pd.to_datetime(
    df["this_period_clean"].astype(str),
    format="%Y%m"
)

df[["this_period_clean", "date"]].head()

   this_period_clean       date
0             202412 2024-12-01
1             202412 2024-12-01
2             202412 2024-12-01
3             202412 2024-12-01
4             202412 2024-12-01

In [13]:
df["month_year"] = df["date"].dt.strftime("%B %Y")

df[["date", "month_year"]].head()

        date     month_year
0 2024-12-01  December 2024
1 2024-12-01  December 2024
2 2024-12-01  December 2024
3 2024-12-01  December 2024
4 2024-12-01  December 2024

In [14]:
df.duplicated(
    subset=["date", "reporting_airport_name"]
).sum()

np.int64(0)

In [15]:
df["reporting_airport_name"].nunique()

114

In [16]:
df.groupby("reporting_airport_name")["total_pax_this_period"].sum().sort_values(
    ascending=False
).head(10)

reporting_airport_name
HEATHROW                          648270582
GATWICK                           349216195
MANCHESTER                        232013958
STANSTED                          226482720
LUTON                             137544392
EDINBURGH                         117291859
BIRMINGHAM                        100463118
HEATHROW                           91779220
BRISTOL                            75749093
GLASGOW                            70106073
Name: total_pax_this_period, dtype: int64

In [17]:
df.loc[
    df["reporting_airport_name"].str.contains("HEATHROW"),
    "reporting_airport_name"
].unique()

<ArrowStringArray>
['HEATHROW', 'HEATHROW                      ']
Length: 2, dtype: str

In [18]:
df["reporting_airport_name"] = df["reporting_airport_name"].str.strip()

df["reporting_airport_name"].nunique()

59

In [19]:
df.groupby("reporting_airport_name")["total_pax_this_period"].sum().sort_values(
    ascending=False
).head(10)

reporting_airport_name
HEATHROW                 740049802
GATWICK                  397800981
MANCHESTER               259809055
STANSTED                 254227306
LUTON                    152550087
EDINBURGH                130802515
BIRMINGHAM               112872769
BRISTOL                   83894433
GLASGOW                   80613828
BELFAST INTERNATIONAL     56184716
Name: total_pax_this_period, dtype: int64

In [20]:
df["reporting_airport_group_name"] = (
    df["reporting_airport_group_name"].str.strip()
)

In [21]:
df["reporting_airport_group_name"].unique()

<ArrowStringArray>
['Other UK Airports', 'Non UK Reporting Airports', 'London Area Airports']
Length: 3, dtype: str

In [22]:
df.isna().sum()

rundate                         0
this_period                     0
last_period                     0
reporting_airport_group_name    0
reporting_airport_name          0
total_pax_this_period           0
total_pax_last_period           0
total_pax_percent               0
terminal_pax_this_period        0
terminal_pax_last_period        0
terminal_pax_percent            0
transit_pax_this_period         0
transit_pax_last_period         0
transit_pax_percent             0
this_period_clean               0
date                            0
month_year                      0
dtype: int64

In [23]:
(df == "Null").sum()

rundate                            0
this_period                        0
last_period                        0
reporting_airport_group_name       0
reporting_airport_name             0
total_pax_this_period              0
total_pax_last_period              0
total_pax_percent                298
terminal_pax_this_period           0
terminal_pax_last_period           0
terminal_pax_percent             301
transit_pax_this_period            0
transit_pax_last_period            0
transit_pax_percent             4675
this_period_clean                  0
date                               0
month_year                         0
dtype: int64

In [24]:
aviation = df[[
    "date",
    "month_year",
    "reporting_airport_group_name",
    "reporting_airport_name",
    "total_pax_this_period",
    "terminal_pax_this_period",
    "transit_pax_this_period"
]].copy()

aviation.head()

,date,month_year,reporting_airport_group_name,reporting_airport_name,total_pax_this_period,terminal_pax_this_period,transit_pax_this_period
0,2024-12-01,December 2024,Other UK Airports,ABERDEEN,169354,169354,0
1,2024-12-01,December 2024,Non UK Reporting Airports,ALDERNEY,2815,2815,0
2,2024-12-01,December 2024,Other UK Airports,BARRA,476,476,0
3,2024-12-01,December 2024,Other UK Airports,BELFAST CITY (GEORGE BEST),189157,189089,68
4,2024-12-01,December 2024,Other UK Airports,BELFAST INTERNATIONAL,495809,495809,0

In [25]:
aviation = aviation.rename(columns={
    "reporting_airport_group_name": "airport_group",
    "reporting_airport_name": "airport",
    "total_pax_this_period": "total_passengers",
    "terminal_pax_this_period": "terminal_passengers",
    "transit_pax_this_period": "transit_passengers"
})

aviation.head()

,date,month_year,airport_group,airport,total_passengers,terminal_passengers,transit_passengers
0,2024-12-01,December 2024,Other UK Airports,ABERDEEN,169354,169354,0
1,2024-12-01,December 2024,Non UK Reporting Airports,ALDERNEY,2815,2815,0
2,2024-12-01,December 2024,Other UK Airports,BARRA,476,476,0
3,2024-12-01,December 2024,Other UK Airports,BELFAST CITY (GEORGE BEST),189157,189089,68
4,2024-12-01,December 2024,Other UK Airports,BELFAST INTERNATIONAL,495809,495809,0

In [26]:
aviation = aviation.sort_values(
    by=["date", "airport"]
).reset_index(drop=True)

aviation.head()

,date,month_year,airport_group,airport,total_passengers,terminal_passengers,transit_passengers
0,2015-01-01,January 2015,Other UK Airports,ABERDEEN,249165,249165,0
1,2015-01-01,January 2015,Non UK Reporting Airports,ALDERNEY,2906,2906,0
2,2015-01-01,January 2015,Other UK Airports,BARRA,437,437,0
3,2015-01-01,January 2015,Other UK Airports,BELFAST CITY (GEORGE BEST),167662,167662,0
4,2015-01-01,January 2015,Other UK Airports,BELFAST INTERNATIONAL,237948,237819,129

In [27]:
aviation.shape

(6758, 7)

In [28]:
aviation.to_csv(
    "../data/processed/aviation_clean.csv",
    index=False
)